### ISSUE TITLE
How do the "model_best.hdf5" be generated?

### ISSUE THREAD

**Issue by Albelt** [xmengli999/H-DenseUNet#10]
Hi!

I have followed the procedure in README:
   1. load "densenet161_weights_tf.h5" and train 2D DenseUNet.
   2. load "model_best.hdf5" and train 3dpart H-DenseUNet.
   3. load "model_best.hdf5" and train end2end H-DenseUNet.

Since I just simply download your fine-trained model's weights, it seems that I haven't go through the completed procedure as you do. 

I wonder how do you generate file "model_best.hdf5", my understanding is as follow, could you please correct it? Thank you very much!
1. train 2d part of H-DenseUNet 
          load "densenet161_weights_tf.h5" and train 2D DenseUNet, train and save all epochs' weight

2. train 3d part and HFF part of  H-DenseUNet 
          load the best epoch's weight from "1"(2d part), set 2d part of H-DenseUNet to be untrainable, just 
          train 3d part and HFF part of H-DenseUNet, train and save all epochs' weight

3. fine tune H-DenseUNet 
          load the best epoch's weight from "2"(the whole H-DenseUNet), set 2d part of H-DenseUNet to be 
          trainable, train and save all epochs' weight. (since all componets of H-DenseUNet are already be 
          trained, the "end2end" mode is doing the fine tune work, is my comprehesion right?)

4. the best epoch's weight from "3" becomes the file "model_best.hdf5"

**Comment by WdBlink** [comment]
> Hi!
> 
> I have followed the procedure in README:
> 
> 1. load "densenet161_weights_tf.h5" and train 2D DenseUNet.
> 2. load "model_best.hdf5" and train 3dpart H-DenseUNet.
> 3. load "model_best.hdf5" and train end2end H-DenseUNet.
> 
> Since I just simply download your fine-trained model's weights, it seems that I haven't go through the completed procedure as you do.
> 
> I wonder how do you generate file "model_best.hdf5", my understanding is as follow, could you please correct it? Thank you very much!
> 
> 1. train 2d part of H-DenseUNet
>    load "densenet161_weights_tf.h5" and train 2D DenseUNet, train and save all epochs' weight
> 2. train 3d part and HFF part of  H-DenseUNet
>    load the best epoch's weight from "1"(2d part), set 2d part of H-DenseUNet to be untrainable, just
>    train 3d part and HFF part of H-DenseUNet, train and save all epochs' weight
> 3. fine tune H-DenseUNet
>    load the best epoch's weight from "2"(the whole H-DenseUNet), set 2d part of H-DenseUNet to be
>    trainable, train and save all epochs' weight. (since all componets of H-DenseUNet are already be
>    trained, the "end2end" mode is doing the fine tune work, is my comprehesion right?)
> 4. the best epoch's weight from "3" becomes the file "model_best.hdf5"

Hi，could you tell me how to set 2d part of H-DenseUNet to be untrainable and just
    train 3d part and HFF part of H-DenseUNet?After I finished the training of  2D DenseUNet and got the model_best.hdf5, I run the train_hybrid.py and I got this error:`ValueError: You are trying to load a weight file containing 494 layers into a model with 682 layers.`Do you know what's wrong?

**Comment by Apple-zly** [comment]
> > Hi!
> > I have followed the procedure in README:
> > 
> > 1. load "densenet161_weights_tf.h5" and train 2D DenseUNet.
> > 2. load "model_best.hdf5" and train 3dpart H-DenseUNet.
> > 3. load "model_best.hdf5" and train end2end H-DenseUNet.
> > 
> > Since I just simply download your fine-trained model's weights, it seems that I haven't go through the completed procedure as you do.
> > I wonder how do you generate file "model_best.hdf5", my understanding is as follow, could you please correct it? Thank you very much!
> > 
> > 1. train 2d part of H-DenseUNet
> >    load "densenet161_weights_tf.h5" and train 2D DenseUNet, train and save all epochs' weight
> > 2. train 3d part and HFF part of  H-DenseUNet
> >    load the best epoch's weight from "1"(2d part), set 2d part of H-DenseUNet to be untrainable, just
> >    train 3d part and HFF part of H-DenseUNet, train and save all epochs' weight
> > 3. fine tune H-DenseUNet
> >    load the best epoch's weight from "2"(the whole H-DenseUNet), set 2d part of H-DenseUNet to be
> >    trainable, train and save all epochs' weight. (since all componets of H-DenseUNet are already be
> >    trained, the "end2end" mode is doing the fine tune work, is my comprehesion right?)
> > 4. the best epoch's weight from "3" becomes the file "model_best.hdf5"
> 
> Hi，could you tell me how to set 2d part of H-DenseUNet to be untrainable and just
> train 3d part and HFF part of H-DenseUNet?
> After I finished the training of 2D DenseUNet and got the model_best.hdf5, I run the train_hybrid.py and I got this error:`ValueError: You are trying to load a weight file containing 494 layers into a model with 682 layers.`Do you know what's wrong?

Hello, I also have the same question. Do you solve this question? Can you tell me how to solve?

**Comment by Pooja267** [comment]
> > > Hi!
> > > I have followed the procedure in README:
> > > 
> > > 1. load "densenet161_weights_tf.h5" and train 2D DenseUNet.
> > > 2. load "model_best.hdf5" and train 3dpart H-DenseUNet.
> > > 3. load "model_best.hdf5" and train end2end H-DenseUNet.
> > > 
> > > Since I just simply download your fine-trained model's weights, it seems that I haven't go through the completed procedure as you do.
> > > I wonder how do you generate file "model_best.hdf5", my understanding is as follow, could you please correct it? Thank you very much!
> > > 
> > > 1. train 2d part of H-DenseUNet
> > >    load "densenet161_weights_tf.h5" and train 2D DenseUNet, train and save all epochs' weight
> > > 2. train 3d part and HFF part of  H-DenseUNet
> > >    load the best epoch's weight from "1"(2d part), set 2d part of H-DenseUNet to be untrainable, just
> > >    train 3d part and HFF part of H-DenseUNet, train and save all epochs' weight
> > > 3. fine tune H-DenseUNet
> > >    load the best epoch's weight from "2"(the whole H-DenseUNet), set 2d part of H-DenseUNet to be
> > >    trainable, train and save all epochs' weight. (since all componets of H-DenseUNet are already be
> > >    trained, the "end2end" mode is doing the fine tune work, is my comprehesion right?)
> > > 4. the best epoch's weight from "3" becomes the file "model_best.hdf5"
> > 
> > 
> > Hi，could you tell me how to set 2d part of H-DenseUNet to be untrainable and just
> > train 3d part and HFF part of H-DenseUNet?
> > After I finished the training of 2D DenseUNet and got the model_best.hdf5, I run the train_hybrid.py and I got this error:`ValueError: You are trying to load a weight file containing 494 layers into a model with 682 layers.`Do you know what's wrong?
> 
> Hello, I also have the same question. Do you solve this question? Can you tell me how to solve?

Same problem here. Please post the solution if found.

**Comment by Pooja267** [comment]
I added the parameter by_name=True in the below line model.load_weights(args.model_weight,by_name=True). The error got resolved.
