### ISSUE TITLE
question about testing scheme

### ISSUE THREAD

**Issue by Wang-Shuo** [xmengli999/H-DenseUNet#11]
Hi. Thanks for your code.
The test.py script is for H-DenseUNet. In that script, it seems that you slide a box sized 1x512x512x8x1 along the z-axis to make the prediction. the step size is 2. 

Recently I'm implementing your code in pytorch, I want to test on 2D DenseUNet, I'm wondering that if testing on 2D DenseUNet follows the similar scheme, that is to say:  
Find leftmost and rightmost z coordinates based on the coarse liver mask, 
Then slide a box sized 1x512x512x3 along the z-axis to make the prediction on the middle slice. the step size is set up to 1. 

is that correct? thanks!

**Comment by xmengli999** [comment]
Yes, you are correct.  Using the coarse liver mask aims to increase the test efficiency.
