### ISSUE TITLE
Question about the liver ROI with 224x224

### ISSUE THREAD

**Issue by lancexiang** [xmengli999/H-DenseUNet#13]
Here the paper refs:
> With the region of interest (ROI), our proposed H-DenseUNet efficiently probes...

After i read the code, i find that the `224x224` ROI is generated by 'resize' function, which confuse me a little. Can you explain this distinction to me? 

What's more? There is a doubt that what should i do if i just want to test the `2D-DenseUNet` instead of `H-DenseUNet` while your training strategy is accessed to `224x224`, should i be violent to use the origin resolution of `512x512` to the `2D-DenseUNet` test? How can i solve this problem? 

Wish to a reply in the new year~

Last, Happy New Years~

**Comment by xmengli999** [comment]
Hi, in the paper, the region of interest denotes the regions that contains liver only. In the code, the files in "LiverBox" denotes the regions. 

To test the result, you can directly use 512*512. 
If you want to test 2D-DenseUnet, you should test each slice and then concatenate to a 3d volume. Other post-processing is the same with H-DenseUnet.

**Comment by lancexiang** [comment]
Thanks for youe rapid reply! Here're some detail question about the magic number, i think this denote the slices within liver(about 18000)  and tumor(about 8500), whatever i can't get the magic number 27386, and in the test of H-DenseUNet, the paper have a size of 224*224*12,but the code seems to be 224*224*8,is it correct?

**Comment by lancexiang** [comment]
OK, i will. By the way, it is unbelievable, i find you are my sister school. i'm the 2014-class student in Xi'dian. The idea for your paper is so excellent, hybrid future of 2D and 3D. So what i want to do is to re-implement the result of your paper published in IEEE Trans. Medical Image.  I will try my best to learn for you, thanks for your reply again! 

Happy new year~

**Comment by xmengli999** [comment]
What a coincidence! The code is .. just an initial version and still need to organize.
I released it since many people asked and may provide a clear and pellucid version later.  Sorry for the inconvenience and misunderstanding caused.
Happy new year!
