### ISSUE TITLE
About the test dataset 

### ISSUE THREAD

**Issue by ericyeyeye** [xmengli999/H-DenseUNet#15]
In the LiTS google cloud, there is not a folder for test data. All of the images(131) are for the training. When I run the test.py the livermask dimension is not the same as the test data. I want to know where do you get the test dataset? Or can you tell me what is the dataset you use for the coarse mask? Thanks a lot.

**Comment by andebana1** [comment]
Hi, Eric. I'm using the dataset available at http://medicaldecathlon.com. It seems to have all the same files than the original LiTS dataset. You just will need make some adjusts in the code, nothing much. Hope it help you.

**Comment by ericyeyeye** [comment]
Thanks a lot andebana1!!! That would be very helpful for me.
