### ISSUE TITLE
How get the 3D display as shown in paper Figure1?

### ISSUE THREAD

**Issue by shipengai** [xmengli999/H-DenseUNet#19]
Thanks for your share .
How get the 3D display as shown in paper Figure1?
Which software?
I am looking forward your reply .
thanks

**Comment by EdwardMa12593** [comment]
[ITK-Snap](http://www.itksnap.org/pmwiki/pmwiki.php)
BTW, I recommend the STABLE VERSION (3.6.0).

**Comment by shipengai** [comment]
> [ITK-Snap](http://www.itksnap.org/pmwiki/pmwiki.php)
> BTW, I recommend the STABLE VERSION (3.6.0).

Thanks
