### ISSUE TITLE
slow training

### ISSUE THREAD

**Issue by leetesua** [xmengli999/H-DenseUNet#29]
When i run train_2ddense.py, every epoch takes more than 1000s. I use 2 GPUs so I changed the '-b' paramaters to be 20 instead of 40. And Considering the total epoch is set to be 6000, the whole training process could take months. 

**Is that normal? How could I speeeeed up? Thanks in advance!**

**Comment by xmengli999** [comment]
The model would converge before 6000 epoch. I forgot the exact epoch. Normally, it takes 2-3days using 4 GPUs.
