### ISSUE TITLE
Just a little question about multi-gpu model

### ISSUE THREAD

**Issue by aa1234241** [xmengli999/H-DenseUNet#35]
Hello, 
in your code, you write your own mult-gpu model. I am a little confused since keras has native multi-gpu support. Is there any problem to use the parallel model in original Keras?

Sincerely

**Comment by leetesua** [comment]
same here

**Comment by xmengli999** [comment]
You can use the Keras in this code. It contains the multi-gpu function.

**Comment by aa1234241** [comment]
Thank you very much.
