### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by leetesua** [xmengli999/H-DenseUNet#36]
Hello xmengli, I have an issue when run your program:

When run test.py, I got out of memory error. Some test cases are OK but some cases are too big that I got a ResourceExhaustedError. 

My Mem is 126G, so I think it is big enough. Any idea about how to solve it? 

thanks in advance！

**Comment by leetesua** [comment]
it happens when ' Predicting masks on test data... '

**Comment by xmengli999** [comment]
Could you take a figure for the error?

**Comment by leetesua** [comment]
![image](https://user-images.githubusercontent.com/25045281/59415754-a9b20c00-8df6-11e9-8f5f-d850c6c9ed3b.png)

**Comment by anxingle** [comment]
@leetesua   So, how did U solve the problem？

**Comment by jucyLL** [comment]
Did you solve the problem?
