### ISSUE TITLE
some question about the layer box in denseunet in your code

### ISSUE THREAD

**Issue by Duffyxx** [xmengli999/H-DenseUNet#37]
In the general UNet, layer will be appended to the layer box while down sampling, and concated with the feature map while up sampling, In your code, I think layers in layer box will be added to the decoder feature map, but I found that you did nothing with layer box while up sampling, could you please explain the reason about that? Thanks.

**Comment by xmengli999** [comment]
This code shows the densenet without unet connection. I also add the version of densenet with unet connection that we use in our paper. You can retrain the network with these two backbones, and can see the differences.

**Comment by Duffyxx** [comment]
I see, thanks.
