### ISSUE TITLE
nb_filter parameter in function DenseUNet is useless.

### ISSUE THREAD

**Issue by linchundan88** [xmengli999/H-DenseUNet#4]
nb_filter parameter in function DenseUNet is useless.   Because in the body of function:
    nb_filter = 96
    nb_layers = [6,12,36,24] # For DenseNet-161 
    ...

**Comment by linchundan88** [comment]
and classes: optional number of classes to classify images
But you use a fix number "x = Conv2D(3, (1,1),  

parameter weights_path=None, but  this parameter is useless.

**Comment by xmengli999** [comment]
Yes, you can ignore them.
