### ISSUE TITLE
liver mask

### ISSUE THREAD

**Issue by charlesyou999648** [xmengli999/H-DenseUNet#5]
As you mentioned in your paper, 

> A simple ResNet is trained to get a quick but coarse segmentation of liver

Thus, I am wondering whether the liver masks which are given in the [README](https://github.com/xmengli999/H-DenseUNet/blob/master/README.md) should be the generated liver mask?

Thank you very much!

**Comment by xmengli999** [comment]
Yes.  the given liver mask is generated from a simple ResNet.

**Comment by charlesyou999648** [comment]
Thanks a lot!
