### ISSUE TITLE
is possible to run load_fast_files() in  train_2ddense.py?

### ISSUE THREAD

**Issue by dzfowen** [xmengli999/H-DenseUNet#6]
It seems to load 131 volumes once in RAM, which needs optimization and cannot run in a normal server.

**Comment by xmengli999** [comment]
Loading 131 volumes once in RAM can save training time. Alternatively, you can load image path only and read images when training the network.

**Comment by dzfowen** [comment]
thanks  what about 131 lines liverlist[] meaning in train_2ddense.py?

**Comment by xmengli999** [comment]
The index in liverlist is the data case that does not contain tumor.
