### ISSUE TITLE
Some inconsistencies between the paper and the code.

### ISSUE THREAD

**Issue by whoops33** [xmengli999/H-DenseUNet#9]
Hi,
I read your paper _H-DenseUNet: Hybrid Densely Connected UNet for Liver and Tumor Segmentation from CT Volumes_ and find some inconsistencies between the network structure in your paper and the released code.
(1) In the Table I of your paper, the upsampling layers of 2D DenseUNet or 3D DenseUNet is composed of  a 2x2 upsampling and a dense block, while in the code, the upsampling layers are composed of a 2x2 upsampling and only one convolution (for example, see the line 154 and line 241 in hybridnet.py).
(2) Meanwhile, in your released code, I notice that the UNet-like connections in the 3D DenseUNet are commented out (see the line 153 in hybridnet.py), which is not the same as it in your paper.
Could you please help me figure it out?

**Comment by xmengli999** [comment]
For question 1, '-' in table 1 denotes sum connections with the end layer of the dense block. The features are added with each dense block in the encoder part.
For question 2, the main contribution of the paper is the hybrid usage of 2D convolution and 3D convolution. The usage of the u-net connection maybe better in the hybrid training. However, for simplicity, the released test model for you to reproduce the results is the one that tested without u-net connection.

**Comment by whoops33** [comment]
OK, Thanks for your help. 
No offense but it means I can reproduce the results even with this simple version of H-DenseUNet, right?

**Comment by xmengli999** [comment]
exactly

**Comment by whoops33** [comment]
Thanks!
